name: 常规任务派发

on:
  schedule:
    - cron: '0 * * * *'   # 0 * * * *   ← 每小时执行一次    */30 * * * * ← 每30分钟执行一次   0 8 * * *   ← 每天早上8点执行
  workflow_dispatch:       # 允许手动触发

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: 调用任务派发接口
        run: |
          curl -X GET "https://www.55dui.com/api/cron.php"
